// Package scenario defines what the agent is asked to diagnose and what
// counts as getting it right.
//
// # The alert is generated, never authored
//
// A scenario does not carry alert text. The runner composes it at execution time
// from metrics measured on the symptom service after injection.
//
// This is a leak-proof measure, not a convenience. Hand-written alert text
// drifts toward the answer -- "payment is returning errors" is most of the
// diagnosis, and paymentUnreachable's whole difficulty is that the symptom
// appears on checkout while payment merely looks absent. Generating the alert
// from observed symptoms makes leaking the root cause impossible by
// construction, and matches what an alerting system would actually deliver.
//
// # Only verified faults belong here
//
// Scenarios are generated from characterisation output, so a fault that failed
// verification cannot enter the library by hand. An unverified fault produces a
// scenario that looks injected but is not, and that scenario scores the agent
// against a healthy system while nothing anywhere reports a failure.
package scenario

import (
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// Fault is one flag set to one variant.
type Fault struct {
	Flag    string `yaml:"flag"`
	Variant string `yaml:"variant"`
}

func (f Fault) String() string { return f.Flag + "=" + f.Variant }

// GroundTruth is what the agent is scored against.
//
// Deliberately coarse. Root cause is a service and a fault class, not a
// sentence: a free-text cause would need a judge, and a judged benchmark is one
// whose numbers cannot be reproduced by anyone else.
type GroundTruth struct {
	// RootCauseService is the service at fault. Empty for a healthy control,
	// where the correct answer is that nothing is wrong.
	RootCauseService string `yaml:"root_cause_service"`
	// RootCauseClass is one of the fault classes: error, latency, resource,
	// connectivity, health, queue.
	RootCauseClass string `yaml:"root_cause_class"`
	// SymptomService is where the alert fires. Recorded to measure whether the
	// agent traced from symptom to cause, or merely repeated the symptom back.
	SymptomService string `yaml:"symptom_service"`
	// Healthy marks a control scenario with no fault injected.
	Healthy bool `yaml:"healthy"`
}

// Scenario is one episode.
type Scenario struct {
	ID          string      `yaml:"id"`
	Description string      `yaml:"description"`
	Difficulty  string      `yaml:"difficulty"`
	Faults      []Fault     `yaml:"faults"`
	Truth       GroundTruth `yaml:"ground_truth"`

	// SettleSeconds is how long to wait after injection before alerting, so the
	// symptom is actually present in the metrics the agent will query.
	SettleSeconds int `yaml:"settle_seconds"`
	// RecoverSeconds is how long to wait after reverting before the next
	// scenario, so this fault's tail does not contaminate the next baseline.
	RecoverSeconds int `yaml:"recover_seconds"`
	// MaxSteps bounds the agent's tool calls, so a looping agent cannot stall
	// the run.
	MaxSteps int `yaml:"max_steps"`

	// Signal and Subs name the measurement used to confirm the fault took
	// effect in this episode, carried over from characterisation. A scenario
	// whose fault fails to fire is discarded rather than scored.
	Signal string            `yaml:"signal"`
	Subs   map[string]string `yaml:"subs"`
	// ExpectedDelta is the shift characterisation measured for this fault, kept
	// as a sanity reference for the per-episode check.
	ExpectedDelta float64 `yaml:"expected_delta"`
	MinDelta      float64 `yaml:"min_delta"`

	Notes string `yaml:"notes,omitempty"`
}

func (s Scenario) Settle() time.Duration {
	return time.Duration(s.SettleSeconds) * time.Second
}

func (s Scenario) Recover() time.Duration {
	return time.Duration(s.RecoverSeconds) * time.Second
}

// Library is a set of scenarios plus how it was produced.
type Library struct {
	GeneratedFrom string     `yaml:"generated_from"`
	Scenarios     []Scenario `yaml:"scenarios"`
}

// Load reads and validates a scenario library.
func Load(path string) (*Library, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read scenario library %s: %w", path, err)
	}
	var lib Library
	if err := yaml.Unmarshal(b, &lib); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if err := lib.Validate(); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &lib, nil
}

// Save writes a library.
func (l *Library) Save(path string) error {
	b, err := yaml.Marshal(l)
	if err != nil {
		return err
	}
	header := "# Generated by `go run ./cmd/scenarios`. Do not edit by hand.\n" +
		"#\n" +
		"# Only faults that passed both tiers of characterisation appear here. A\n" +
		"# fault added by hand without verification yields a scenario that looks\n" +
		"# injected but is not, and it would score the agent against a healthy\n" +
		"# system with nothing anywhere reporting a failure.\n" +
		"#\n" +
		"# Alert text is absent on purpose: the runner composes it from metrics\n" +
		"# measured after injection, so it cannot leak the root cause.\n\n"
	return os.WriteFile(path, append([]byte(header), b...), 0o644)
}

// Validate rejects a library that would produce meaningless scores.
func (l *Library) Validate() error {
	if len(l.Scenarios) == 0 {
		return fmt.Errorf("library contains no scenarios")
	}
	seen := map[string]bool{}
	var problems []string

	for i, s := range l.Scenarios {
		where := fmt.Sprintf("scenario %d", i)
		if s.ID == "" {
			problems = append(problems, where+": missing id")
			continue
		}
		where = s.ID
		if seen[s.ID] {
			problems = append(problems, where+": duplicate id")
		}
		seen[s.ID] = true

		if s.MaxSteps <= 0 {
			problems = append(problems, where+": max_steps must be positive")
		}
		if s.SettleSeconds <= 0 {
			problems = append(problems, where+": settle_seconds must be positive, "+
				"or the agent is asked about a symptom that has not appeared yet")
		}

		if s.Truth.Healthy {
			if len(s.Faults) > 0 {
				problems = append(problems, where+
					": marked healthy but injects faults")
			}
			if s.Truth.RootCauseService != "" {
				problems = append(problems, where+
					": marked healthy but names a root cause service")
			}
			continue
		}

		if len(s.Faults) == 0 {
			problems = append(problems, where+
				": no faults and not marked healthy; the agent would be scored "+
				"on a system nothing was done to")
		}
		if s.Truth.RootCauseService == "" || s.Truth.RootCauseClass == "" {
			problems = append(problems, where+
				": ground truth needs both a root cause service and class")
		}
		if s.Signal == "" {
			problems = append(problems, where+
				": no signal, so there is no way to confirm the fault fired")
		}
		if s.MinDelta <= 0 {
			problems = append(problems, where+
				": min_delta must be positive, or any noise confirms the fault")
		}
		for _, f := range s.Faults {
			if f.Flag == "" || f.Variant == "" {
				problems = append(problems, where+": fault needs both flag and variant")
			}
		}
	}

	if len(problems) > 0 {
		return fmt.Errorf("invalid library:\n  %s", strings.Join(problems, "\n  "))
	}
	return nil
}

// Filter returns scenarios whose IDs match, or all of them when ids is empty.
func (l *Library) Filter(ids []string) []Scenario {
	if len(ids) == 0 {
		return l.Scenarios
	}
	want := map[string]bool{}
	for _, id := range ids {
		want[strings.TrimSpace(id)] = true
	}
	var out []Scenario
	for _, s := range l.Scenarios {
		if want[s.ID] {
			out = append(out, s)
		}
	}
	return out
}

// Summary counts scenarios by difficulty and kind, for a run header.
func (l *Library) Summary() string {
	byDifficulty := map[string]int{}
	healthy, multi := 0, 0
	for _, s := range l.Scenarios {
		byDifficulty[s.Difficulty]++
		if s.Truth.Healthy {
			healthy++
		}
		if len(s.Faults) > 1 {
			multi++
		}
	}
	keys := make([]string, 0, len(byDifficulty))
	for k := range byDifficulty {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		label := k
		if label == "" {
			label = "unclassified"
		}
		parts = append(parts, fmt.Sprintf("%s=%d", label, byDifficulty[k]))
	}
	return fmt.Sprintf("%d scenarios (%s; %d healthy controls, %d multi-fault)",
		len(l.Scenarios), strings.Join(parts, " "), healthy, multi)
}

// EstimatedDuration is the wall clock a full run needs, excluding agent time.
func (l *Library) EstimatedDuration() time.Duration {
	var total time.Duration
	for _, s := range l.Scenarios {
		total += s.Settle() + s.Recover()
	}
	return total
}
